# Generated by Django 5.2.4 on 2025-09-28 07:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradeRiskSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('take_profit_percent', models.FloatField(default=2.0, help_text='Take profit % per trade (e.g., 2.0 = +2%)')),
                ('stop_loss_percent', models.FloatField(default=1.0, help_text='Stop loss % per trade (e.g., 1.0 = -1%)')),
                ('trailing_stop_percent', models.FloatField(default=0.5, help_text='Trailing stop % from peak (e.g., 0.5 = -0.5%)')),
                ('max_holding_minutes', models.IntegerField(default=720, help_text='Maximum holding time in minutes (default = 12h)')),
                ('risk_per_trade_percent', models.FloatField(default=1.0, help_text='Portfolio % to risk per trade (for position sizing)')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_settings', to='dashboard.tradelog')),
            ],
        ),
    ]
