# Generated by Django 5.2.4 on 2025-09-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_botstatus_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinprediction',
            name='coin',
        ),
        migrations.RemoveField(
            model_name='coinprediction',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='coinprediction',
            name='ema200',
        ),
        migrations.RemoveField(
            model_name='coinprediction',
            name='next_check',
        ),
        migrations.RemoveField(
            model_name='coinprediction',
            name='price',
        ),
        migrations.RemoveField(
            model_name='coinprediction',
            name='rsi',
        ),
        migrations.RemoveField(
            model_name='coinprediction',
            name='signal',
        ),
        migrations.RemoveField(
            model_name='coinprediction',
            name='volume_spike',
        ),
        migrations.AddField(
            model_name='coinprediction',
            name='log',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='coinprediction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
